spring:
  servlet:
    # ??????????
    multipart:
      enabled: true # ??????
      max-file-size: 20MB # ?????????
      max-request-size: 20MB # ????????
  # ???????
  datasource:
    name: test  #????
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&useSSL=false #url
    username: root  #???
    password: root  #??
    driver-class-name: com.mysql.jdbc.Driver  #???????

  # ????
server:
  port: 80

#??????
uploadPath:
  # ?????????????Windows??C?????Linux??????../?
  realFolder: /media/web/imgLogo/
  # ????????????http://localhost/upload/logo/xxx.jpg
  reflexFolder: /upload/logo/

# Mybatis-Plus ?????
mybatis:
  mapper-locations: classpath*:mapper/**/*Mapper.xml # ??mapper?????????mapper.xml????
  type-aliases-package: com.example.uploadfile.entity # ???????---?????
  #  config-location: classpath:mybatis-config.xml  # ???????????config-location???configuration??????????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # ????????,??MyBatis?????????
    cache-enabled: false # ?????????????????????????????????????true
    map-underscore-to-camel-case: true # ????????????????????????????????????false
    auto-mapping-behavior: full # ??MyBatis???????????????,????PARTIAL???????NONE, PARTIAL, FULL?NONE??????????PARTIAL?????????????????????FULL??????????????????????
    use-generated-keys: false # ???????????????false
    default-executor-type: reuse # ??MyBatis?????????????REUSE?????BATCH?????SIMPLE?????CUSTOMIZE?????
    default-fetch-size: 100 # ??MyBatis???????????????100 ???????????????????fetchsize????????????Fetchsize???????????????????????????????????????????????????????
